name: hello-contributor
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  explore-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Hello From ${{ github.repository_owner }}."
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Hello world action step
        id: hello
        uses: ./
        with:
          milliseconds: 2000
