name: enforce-coding-standards-and-guidelines

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint-codebase:
    name: lint-codebase
    runs-on: ubuntu-latest

    steps:
      - name: checkout-repository
        id: checkout
        uses: actions/checkout@v4

      - name: setup-nodejs-environment
        id: setup-node-env
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: "npm"
          cache-dependency-path: package.json

      - name: install-npm-dependencies
        id: install-deps
        run: npm install

      - name: run-super-linter
        id: super-linter
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: entry/**/*
          TYPESCRIPT_DEFAULT_STYLE: prettier
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
