name: test-github-actions-workflow
run-name: ${{ github.actor }} is testing out github actions 🚀
on: [push]
jobs:
  greeting:
    name: display-greeting-message
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Hello ${{ github.actor }}."

  self-inspection:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4

      - name: run-self-inspection
        uses: ./
        if: github.repository == 'al-imam/action-ts-template'
        with:
          milliseconds: 2000
